
export const slideArray = [
  {
    id: 1,
    imgss: "/portfolio1.gif",
    title: "E-commerce website for fashion retailer",
    text: "We developed a visually appealing and user-friendly e-commerce website for a high-end fashion retailer. The site features a seamless shopping experience, secure payment gateways, and an intuitive product catalogue.",
  },
  {
    id: 2,
    imgss: "/portfolio2.gif",
    title: "Mobile App for Health & Fitness Startup",
    text: "We designed and developed a mobile application for a health & fitness startup. The app features workout routines, diet plans, progress trackers, and a community forum.",
  },
  {
    id: 3,
    title: "Mobile App for Health & Fitness Startup",
    imgss: "/portfolio3.gif",
    text: "We developed a visually appealing and user-friendly e-commerce website for a high-end fashion retailer. The site features a seamless shopping experience, secure payment gateways, and an intuitive product catalogue.",
  },
];
export const serviceData = [
  {
    id: 1,
    icon: "/home-srvices-icon1.svg",
    title: "Custom Website Design",
    text: "Our talented team of designers create visually stunning, functional and user-friendly websites that reflect your brand and engage your audience. We focus on creating a seamless user experience that drives conversions and boosts your online presence.",
    link: "/services/ui-ux",
  },
  {
    id: 2,
    icon: "/home-srvices-icon2.svg",
    title: "Website Development",
    text: "We specialize in crafting high-performance websites using the latest technologies and coding standards. Our developers ensure your website is fast, secure, responsive and optimized for search engines.",
    link: "/services/web/custom",
  },
  {
    id: 3,
    icon: "/home-srvices-icon3.svg",
    title: "AI & Machine Learning Solutions",
    text: "Harness the potential of AI and Machine Learning with WebBuddy.agency. Our team of experts can help you integrate intelligent automation, predictive analytics, and data-driven insights into your business processes.",
    link: "/services/ai",
  },
  {
    id: 4,
    icon: "/home-srvices-icon4.svg",
    title: "Website Redesign",
    text: "Need a website makeover? We can revamp your existing website to make it more modern, user-friendly and effective in achieving your business goals.",
    link: "/services/web/web-redesign",
  },
  {
    id: 5,
    icon: "/home-srvices-icon5.svg",
    title: "Website Maintenance",
    text: "Keep your website up-to-date and running smoothly with our website maintenance services. We handle everything from regular updates to troubleshooting, so you can focus on what you do best - running your business. ",
    link: "/services/web/maintenance",
  },
  {
    id: 6,
    icon: "/home-srvices-icon6.svg",
    title: "Blockchain Development",
    text: "Leverage the power of decentralized systems with our Blockchain development services. We design and develop secure, scalable, and custom blockchain solutions to help your business stay ahead in the digital age.",
    link: "/services/blockchain",
  },
  {
    id: 7,
    icon: "/home-srvices-icon7.svg",
    title: "SEO Services",
    text: "Increase your visibility on search engines and attract more organic traffic with our SEO services. We use proven strategies and techniques to improve your website's ranking and reach your target audience. ",
    link: "/services/digital-marketing/seo",
  },
  {
    id: 8,
    icon: "/home-srvices-icon8.svg",
    title: "E-Commerce Solutions",
    text: "From product catalogues to secure payment gateways, we offer end-to-end e-commerce solutions that help you sell your products online with ease and efficiency. ",
    link: "/services/e-commerce",
  },
  {
    id: 9,
    icon: "/home-srvices-icon9.svg",
    title: "IoT Development",
    text: "Connect and automate your business with our IoT development services. We create smart, secure, and scalable IoT solutions that enhance operational efficiency and create new opportunities for growth. ",
    link: "/services/iot",
  },
];
export const ItemArray = [
  {
    id: 2,
    name: "Mobile Application Development",
    section: "section2",
    icons: [
      { icon: "/mobileicon1.png", name: "Swift" },
      { icon: "/mobileicon2.png", name: "Objective-C" },
      { icon: "/mobileicon3.png", name: "Kotlin" },
      { icon: "/mobileicon4.png", name: "Java" },
      { icon: "/mobileicon5.png", name: "React-Native" },
      { icon: "/mobileicon6.png", name: "Flutter" },
      { icon: "/mobileicon7.png", name: "Xamarian" },
      { icon: "/mobileicon8.png", name: "Cordova" },
    ],
  },
  {
    id: 3,
    name: "E-Commerce Solutions",
    section: "section3",
    icons: [
      { icon: "/e1.png", name: "Woocommerce" },
      { icon: "/e2.png", name: "BigCommerce" },
      { icon: "/e3.png", name: "Database Technologies" },
      { icon: "/e4.png", name: "Shopify" },
      { icon: "/e5.png", name: "Magento" },
    ],
  },
  {
    id: 4,
    name: "Ai & Machine Learning",
    section: "section4",
    icons: [
      { icon: "/ai1.png", name: "Tensorflow" },
      { icon: "/ai2.png", name: "Keras" },
      { icon: "/ai3.png", name: "PyTorch" },
      { icon: "/ai4.png", name: "Scikit-Learn" },
    ],
  },
  {
    id: 1,
    name: "Web Development",
    section: "section1",
    icons: [
      { icon: "/web1.png", name: "HTML5" },
      { icon: "/web2.png", name: "CSS3" },
      { icon: "/web3.png", name: "JavaScript" },
      { icon: "/web4.png", name: "React.js" },
      { icon: "/web5.png", name: "Angular" },
      { icon: "/web6.png", name: "Vue.js" },
      { icon: "/web7.png", name: "Node.js" },
      { icon: "/web8.png", name: "Express.js" },
      { icon: "/web9.png", name: "PHP" },
      { icon: "/web10.png", name: "Laravel" },
      { icon: "/web11.png", name: "Symfony" },
      { icon: "/web12.png", name: "Ruby on Rails" },
      { icon: "/web13.png", name: "Django" },
      { icon: "/web14.png", name: "Flask" },
      { icon: "/web15.png", name: "ASPNET" },
    ],
  },
  {
    id: 5,
    name: "BlockChain Development",
    section: "section5",
    icons: [
      { icon: "/block1.png", name: "Ethereum" },
      { icon: "/block2.png", name: "Hyperledger" },
      { icon: "/block3.png", name: "Solidity" },
      { icon: "/block4.png", name: "Truffle" },
    ],
  },
  {
    id: 6,
    name: "UI/UX Design",
    section: "section6",
    icons: [
      { icon: "/ux1.png", name: "Sketch" },
      { icon: "/ux2.png", name: "Adobe XD" },
      { icon: "/ux3.png", name: "Figma" },
      { icon: "/ux4.png", name: "Invision" },
    ],
  },
  {
    id: 7,
    name: "Content Management Systems",
    section: "section7",
    icons: [
      { icon: "/content1.png", name: "WordPress" },
      { icon: "/content2.png", name: "Drupal" },
      { icon: "/content3.png", name: "Joomla" },
      { icon: "/content4.png", name: "Contentful" },
    ],
  },
  {
    id: 8,
    name: "Devops Tools",
    section: "section8",
    icons: [
      { icon: "/devops1.png", name: "Docker" },
      { icon: "/devops2.png", name: "Kubernates" },
      { icon: "/devops3.png", name: "Jenkins" },
      { icon: "/devops4.png", name: "Git.Github" },
      { icon: "/devops5.png", name: "Ansible" },
    ],
  },
  {
    id: 9,
    name: "Cloud Services",
    section: "section9",
    icons: [
      { icon: "/cloud1.png", name: "AWS" },
      { icon: "/cloud2.png", name: "Google Cloud Platform" },
      { icon: "/cloud3.png", name: "Microsoft Azure" },
      { icon: "/cloud4.png", name: "IBM Cloud" },
    ],
  },
  {
    id: 10,
    name: "MySQL",
    section: "section10",
    icons: [
      { icon: "/sql1.png", name: "PostgreSQL" },
      { icon: "/sql2.png", name: "MongoDB" },
      { icon: "/sql3.png", name: "Firebase" },
      { icon: "/sql4.png", name: "Oracle Database" },
    ],
  },
];

export const testimonialData = [
  {
    id: 0,
    img1: "/carousel/c1.png",
    name: "Jimmy Bartney",
    role: "Product Manager at Picko Lab",
    description:
      "I've tried several website builders, but Webbuddy takes the cake. The templates are modern and customizable, and the drag-and-drop interface makes it a breeze to create a stunning website. Love it!",
    companyImage: "It's just incredible!",
  },
  {
    id: 1,
    img1: "/carousel/c1.png",
    name: "Natasha Romanoff",
    role: "Black Widow",
    description:
      "Never thought that with Spend.In managing my business expenses is so easy! Been using this platform for 3 months and still counting!",
    companyImage: "Satisfied User Here!",
  },
  {
    id: 2,
    img1: "/carousel/c1.png",
    name: "Moritika Kazuki",
    role: "Finance Manager at Mangan",
    description:
      "“The best”! That’s what I want to say to this platform, didn’t know that there’s a platform to help you manage your business expenses like this! Very recommended to you who have a big business!",
    companyImage: "No doubt, Spend.In is the best!",
  },
 
];

export const navArray = [
  {
    id: 1,
    category_title: "Home",
    link: "/",
  },
  {
    id: 2,
    category_title: "Services",
    sublinks: [
      {
        title: "Mobile App Development",
        icon_active: "/icona00.png",
        icon_inactive: "/iconw0.png",
        services: [
          { name: "iOS Development", link: "/services/mobile/ios", icon: "/icons/iOS Development.svg" },
          { name: "Android Development", link: "/services/mobile/android", icon: "/icons/Android Development.svg" },
          { name: "React Native App Development", link: "/services/mobile/reactnative", icon: "/icons/React Native App Development.svg" },
          { name: "Cross-Platform App Development", link: "/services/mobile/cross-platform", icon: "/icons/Cross-Platform App Development.svg" },
          { name: "Hybrid App Development", link: "/services/mobile/hybrid", icon: "/icons/Hybrid App Development.svg" },
          { name: "App UI/UX Design", link: "/services/mobile/ui-ux", icon: "/icons/ui UX Design.svg" },
          { name: "App Testing And Quality Assurance", link: "/services/mobile/app-testing", icon: "/icons/App Testing & Quality Assurance.svg" },
          { name: "App Maintainace And Support", link: "/services/mobile/maintenance", icon: "/icons/App Maintenance & Support.svg" },
          { name: "App Consultation And Strategy", link: "/services/mobile/consultation", icon: "/icons/App Consultation & Strategy.svg" },
        ],
      },
      {
        title: "Website Development",
        icon_active: "/icona1.png",
        icon_inactive: "/iconw1.png",
        services: [
          { name: "Custom Website Development", link: "/services/web/custom", icon: "/icons/Custom Website Development.svg" },
          { name: "CMS Development", link: "/services/web/cms", icon: "/icons/CMS Development.svg" },
          { name: "E-Commerce Website Development", link: "/services/web/e-commerce", icon: "/icons/E-commerce Website Development.svg" },
          { name: "Responsive Web Design", link: "/services/web/responsive", icon: "/icons/Responsive Web Design.svg" },
          { name: "UI/UX Design", link: "/services/web/ui-ux", icon: "/icons/ui UX Design.svg" },
          { name: "Website Redesign And Revamp", link: "/services/web/web-redesign", icon: "/icons/Website Redesign & Revamp.svg" },
          { name: "Landing Page Design", link: "/services/web/landing", icon: "/icons/Landing Page Design.svg" },
          { name: "Website Maintainance And Support", link: "/services/web/maintenance", icon: "/icons/Website Maintenance & Support.svg" },
        ],
      },
      {
        title: "Blockchain Development",
        icon_active: "/icona2.png",
        icon_inactive: "/iconw2.png",
        services: [
          {
            name: "BlockChain Consulting And Strategy",
            link: "/services/blockchain/consulting-and-strategy",
            icon: "/icons/Blockchain Consulting & Strategy.svg",
          },
          { name: "Smart Contract Development", link: "/services/blockchain/smart-contract", icon: "/icons/Smart Contract Development.svg" },
          { name: "(DApp) Development", link: "/services/blockchain/dapp", icon: "/icons/(DApp) Development.svg" },
          { name: "Tokenization Solutions", link: "/services/blockchain/tokenization", icon: "/icons/tokenization.svg" },
          {
            name: "Blockchain Integration Services",
            link: "/services/blockchain/intergration-services",
            icon: "/icons/Blockchain Integration Services.svg",
          },
          { name: "Private Blockchain Development", link: "/services/blockchain/private-blockchain", icon: "/icons/Private Blockchain Development.svg" },
          { name: "Public Blockchain Development", link: "/services/blockchain/public-blockchain", icon: "/icons/Public Blockchain Development.svg" },
          { name: "Blockchain Security Audits", link: "/services/blockchain/security-audits", icon: "/icons/Blockchain Security Audits.svg" },
          { name: "CM Design & Implementation", link: "/services/blockchain/cm-design", icon: "/icons/Blockchain CM Design.svg" },
          { name: "Crytocurrency Development", link: "/services/blockchain/cryptocurrency", icon: "/icons/Cryptocurrency Development.svg" },
          { name: "Blockchain Wallet Development", link: "/services/blockchain/wallet-development", icon: "/icons/Blockchain Wallet Development.svg" },
          { name: "Blockchain Testing & QA", link: "/services/blockchain/testing", icon: "/icons/Blockchain Testing & QA.svg" },
        ],
      },
      {
        title: "IOT Development",
        icon_active: "/icona3.png",
        icon_inactive: "/iconw3.png",
        services: [
          { name: "IoT Consulting And Strategy", link: "/services/iot/consultation", icon: "/icons/IoT Consultation & Strategy.svg" },
          { name: "IoT Solution Architecture", link: "/services/iot/solutions", icon: "/icons/IoT Solution Architecture.svg" },
          { name: "IoT Device Integration", link: "/services/iot/intergration", icon: "/icons/IoT Device Integration.svg" },
          { name: "IoT Platform Development", link: "/services/iot/platform", icon: "/icons/IoT Platform Development.svg" },
          { name: "IoT Data Analytics", link: "/services/iot/data-analytics", icon: "/icons/IoT Data Analytics.svg" },
          { name: "IoT Security And Privacy", link: "/services/iot/security", icon: "/icons/IoT Security and Privacy.svg" },
          { name: "IoT Application Development", link: "/services/iot/app-development", icon: "/icons/IoT Application Development.svg" },
          { name: "IoT Cloud Integration", link: "/services/iot/cloud", icon: "/icons/IoT Cloud Integration.svg" },
          { name: "IoT Maintainance And Support", link: "/services/iot/maintenance", icon: "/icons/IoT Maintenance & Support.svg" },
        ],
      },
      {
        title: "AI/ML Development",
        icon_active: "/icona4.png",
        icon_inactive: "/iconw4.png",
        services: [
          { name: "AI/ML Consulting And Strategy", link: "/services/ai/consultation", icon: "/icons/ML Consulting & Strategy.svg" },
          { name: "Natural Language Procesing", link: "/services/ai/nlp", icon: "/icons/Natural Language Processing (NLP).svg" },
          { name: "Computer Vision & Image Recognition", link: "/services/ai/computer-vision", icon: "/icons/Computer Vision & Image Recognition.svg" },
          { name: "Predictive Analytics", link: "/services/ai/predictive-analysis", icon: "/icons/Predictive Analytics.svg" },
          { name: "AI-Powered Chatbots & Virtual Assistants", link: "/services/ai/chatbots", icon: "/icons/AI-powered Chatbots & Virtual Assistants.svg" },
          { name: "Data Science And Analytics", link: "/services/ai/data-science", icon: "/icons/Data Science & Analytics.svg" },
          { name: "AI/ML Algorithm Development", link: "/services/ai/algorithm-development", icon: "/icons/ML Algorithm Development.svg" },
          { name: "AI/ML Model Deployment & Integration", link: "/services/ai/model-deployment", icon: "/icons/ML Model Deployment & Integration.svg" },
          { name: "AI/ML Model Monitoring & Optimization", link: "/services/ai/model-monitoring", icon: "/icons/ML Model Monitoring & Optimization.svg" },
        ],
      },
      {
        title: "E-Commerce Development",
        icon_active: "/icona5.png",
        icon_inactive: "/iconw5.png",
        services: [
          { name: "E-Commerce Website Development", link: "/services/e-commerce", icon: "/icons/E-commerce Website Development.svg" },
          { name: "Payment Gateway Integration", link: "/services/e-commerce/payment-gateway", icon: "/icons/Payment Gateway Integration.svg" },
          { name: "Shopping Cart Development", link: "/services/e-commerce/shopping-cart", icon: "/icons/Shopping Cart Development.svg" },
          { name: "Inventory Management Systems", link: "/services/e-commerce/inventory-management", icon: "/icons/Inventory Management Systems.svg" },
          { name: "Order Management Systems", link: "/services/e-commerce/order-management", icon: "/icons/Order Management Systems.svg" },
          { name: "Multi Channel Selling Solutions", link: "/services/e-commerce/multichannel-selling", icon: "/icons/Multi-channel Selling Solutions.svg" },
          {
            name: "E-Commerce Analytics And Reporting",
            link: "/services/e-commerce/ecommerce-analytics",
            icon: "/icons/E-commerce Analytics & Reporting.svg",
          },
        ],
      },
      {
        title: "UI/UX Design",
        icon_active: "/icona6.png",
        icon_inactive: "/iconw6.png",
        services: [
          { name: "User Interface Design", link: "/services/ui-ux/ui-design", icon: "/icons/User Interface Design.svg" },
          { name: "User Experience Design", link: "/services/ui-ux/ux-design", icon: "/icons/User Experience Design.svg" },
          { name: "Wireframing & Prototyping", link: "/services/ui-ux/wireframing-and-prototyping", icon: "/icons/Wireframing & Prototyping.svg" },
          { name: "Usability Testing", link: "/services/ui-ux/usability-testing", icon: "/icons/Usability Testing.svg" },
          { name: "Mobile App Design", link: "/services/ui-ux/mobileapp-design", icon: "/icons/Mobile App Design.svg" },
          { name: "Web Design", link: "/services/ui-ux/website-design", icon: "/icons/Website Design.svg" },
          { name: "Graphic Design", link: "/services/ui-ux/graphic-design", icon: "/icons/Graphic Design.svg" },
        ],
      },
      {
        title: "Digital Marketing",
        icon_active: "/icona7.png",
        icon_inactive: "/iconw7.png",
        services: [
          { name: "Search Engine Optimization(SEO)", link: "/services/digital-marketing/seo", icon: "/icons/Search Engine Optimization (SEO).svg" },
          { name: "Pay-Per-Click(PPC) Advertising", link: "/services/digital-marketing/pay-per-click", icon: "/icons/Pay-Per-Click (PPC) Advertising.svg" },
          { name: "Content Marketing", link: "/services/digital-marketing/content-marketing", icon: "/icons/Content Marketing.svg" },
          { name: "Email Marketing", link: "/services/digital-marketing/email-marketing", icon: "/icons/Email Marketing.svg" },
          {
            name: "Conversion Rate Optimization(CRO)",
            link: "/services/digital-marketing/conversion-rate",
            icon: "/icons/Conversion Rate Optimization (CRO).svg",
          },
          {
            name: "Online Reputation Management(ORM)",
            link: "/services/digital-marketing/online-reputation",
            icon: "/icons/Online Reputation Management (ORM).svg",
          },
        ],
      },
      {
        title: "Cloud Solutions",
        icon_active: "/icona8.png",
        icon_inactive: "/iconw8.png",
        services: [
          {
            name: "Cloud Infrastructure Setup & Management",
            link: "/services/cloud-solutions/cloud-infrastructure",
            icon: "/icons/Cloud Infrastructure & Management.svg",
          },
          { name: "Cloud Migration Services", link: "/services/cloud-solutions/cloud-migration", icon: "/icons/Cloud Migration Services.svg" },
          { name: "Cloud Application Development", link: "/services/cloud-solutions/cloud-application", icon: "/icons/Cloud Application Development.svg" },
          { name: "Cloud Security And Compliance", link: "/services/cloud-solutions/cloud-security", icon: "/icons/Cloud Security & Compliance.svg" },
          { name: "Serverless Architecture", link: "/services/cloud-solutions/serverless-architecture", icon: "/icons/Serverless Architecture.svg" },
          {
            name: "Scalability & Performance Optimization",
            link: "/services/cloud-solutions/scalability-and-performance",
            icon: "/icons/Scalability & Performance Optimization.svg",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    category_title: "Solutions",
    sublinks: [
      {
        title: "Healthcare",
        icon_inactive: "/sicon1.png",
        icon_active: "/sicona1.png",
        link: "/solutions/healthcare",
      },
      {
        title: "Transportation & Logistics",
        icon_inactive: "/sicon2.svg",
        icon_active: "/sicona2.png",
        link: "/solutions/transport",
      },
      {
        title: "Finance And Banking",
        icon_inactive: "/sicon3.png",
        icon_active: "/sicona3.png",
        link: "/solutions/finance",
      },
      {
        title: "Real Estate",
        icon_inactive: "/sicon4.png",
        icon_active: "/sicona4.png",
        link: "/solutions/real-estate",
      },
      {
        title: "Retail And E-Commerce",
        icon_inactive: "/sicon5.png",
        icon_active: "/sicona5.png",
        link: "/solutions/ecommerce",
      },
      {
        title: "Hospitality And Tourism",
        icon_inactive: "/sicon6.png",
        icon_active: "/sicona6.png",
        link: "/solutions/tourism",
      },
      {
        title: "Education",
        icon_inactive: "/sicon7.png",
        icon_active: "/sicona7.png",
        link: "/solutions/education",
      },
      {
        title: "Energy And Utilities",
        icon_inactive: "/sicon8.png",
        icon_active: "/sicona8.png",
        link: "/solutions/energy",
      },
      {
        title: "Manufacturing",
        icon_inactive: "/sicon9.png",
        icon_active: "/sicona9.png",
        link: "/solutions/manufacturing",
      },
      {
        title: "Media And Entertainment",
        icon_inactive: "/sicon10.png",
        icon_active: "/sicona10.png",
        link: "/solutions/entertainment",
      },
    ],
  },
  {
    id: 4,
    category_title: "Products",
    sublinks: [
      {
        title: "Domain And Web Hosting Platform",
        icon_inactive: "/picon1.png",
        icon_active: "/picona1.png",
        link: "/products/99cents",
      },
      {
        title: "AI-Based Content Writing",
        icon_inactive: "/picon2.svg",
        icon_active: "/picona2.png",
        link: "/products/narratex",
      },
      {
        title: "URL Shortner",
        icon_inactive: "/picon3.png",
        icon_active: "/picona3.png",
        link: "/products/tinytails",
      },
      {
        title: "AdSense Websites",
        icon_inactive: "/picon4.png",
        icon_active: "/picona4.png",
        link: "/products/cookecu",
      },
      {
        title: "File Sharing And Uploading",
        icon_inactive: "/picon5.png",
        icon_active: "/picona5.png",
        link: "/products/uploaditeasy",
      },
      {
        title: "Social Platform",
        icon_inactive: "/picon6.png",
        icon_active: "/picona6.png",
        link: "/products/cookzov",
      },
    ],
  },
  {
    id: 5,
    category_title: "Portfolio",
    link: "/portfolio",
  },
];
